v1
romm80/gophermart pull request #1
Opened 2022-04-26 18:22 UTC by romm80

2022-04-27 05:47 UTC, romm80 commented
Привет!
Это еще не окончательный вариант, пару тестов еще не проходит, из-за загрузка по работе вообще нигде не успеваю(

2022-05-01 21:20 UTC, Barugoo commented on db/migrations/000001_gophermart.up.sql
> +    login character varying PRIMARY KEY,
А что если завтра у нас бизнес придет и скажет, что теперь делаем возможность менять логин юзеру, шо тогда? Я это к тому, что лучше не завязываться на значущие поля при выборе PRIMARY KEY. Давай в каждой табличке добавим `id serial primary key` и будем везде работать исключительно с ним

2022-05-01 21:22 UTC, Barugoo commented on db/migrations/000001_gophermart.up.sql
> +    "number" character varying PRIMARY KEY,
Здесь такая же петрушка - завтра у нас оказывается, что теперь Accrual'ов несколько и у каждого свои айдишники внутри - то есть возможна коллизия и дублирование `PRIMARY KEY` внутри нашей таблицы `orders`. Лучше сделать отдельный айдишник, который не будет иметь никакой бизнес-сути - только так мы можем гарантировать что в будущем не выстрелим сами себе в ногу без возможности быстро и красиво разрулить коллизии.

2022-05-01 21:24 UTC, Barugoo commented on db/migrations/000001_gophermart.up.sql
> +    "user" character varying NOT NULL,
Здесь соответственно можешь сделать `FOREIGN KEY` на табличку `orders`, и такой же для `users`.

2022-05-01 21:25 UTC, Barugoo commented on internal/app/api/api.go
> +	worker := workers.NewAccrualWorker(1000)
Давай сделаем число воркеров конфигурируемым

2022-05-01 21:25 UTC, Barugoo commented on internal/app/api/api.go
> +	user.Use(a.gzipMiddleware)
```go
user.Use(
    a.authMiddleware,
    a.gzipMiddleware,
)

2022-05-01 21:26 UTC, Barugoo commented on internal/app/api/auth.go
> +		}
Давай вынесем маппинг ошибок сервиса в http-статусы в отдельную функцию

2022-05-01 21:27 UTC, Barugoo commented on internal/app/api/auth.go
> +	}
Будто бы генерацию токена мы можем утащить внутрь `service.CreateUser` и возвращать из этого метода первым значением токен, вторым - ошибку

2022-05-01 21:28 UTC, Barugoo commented on internal/app/api/balances.go
> +	err := a.Services.BalancesService.Withdraw(c.GetString("user"), order)
Давай валидировать в хэндлерах то, что нам возвращают функции вроде `c.GetString`, прежде чем передавать значения на нижележащий слой

2022-05-01 21:30 UTC, Barugoo commented on internal/app/models/models.go
> +	PROCESSED  = "PROCESSED"
Несовсем очевидно, к чему относятся данные константы. Я бы объявил отдельный тип и добавил название сущности к которой статусы относятся:
```go
type OrderStatus string

const (
    OrderStatusNew OrderStatus = "NEW"
///..

2022-05-01 21:31 UTC, Barugoo commented on internal/app/models/models.go
> +	Withdrawn float64 `json:"withdrawn"`
Ты правильно хранишь денежные суммы внутри БД в виде `numeric` типа
Но давай тогда и на стороне кода использовать `decimal`

2022-05-01 21:34 UTC, Barugoo commented on internal/app/service/workers/accrual.go
> +				}
Нам незачем инициализировать новый клиент на каждой итерации. Я бы его инициализировал один раз в том месте, где ты плодишь воркеров, и прокидывал этот единственный клиент во все воркеры по указателю.

2022-05-01 21:36 UTC, Barugoo commented on internal/app/service/workers/accrual.go
> +func (r *AccrualWorker) Add(user, order string) {
Несовсем понятно из названия метода, что он делает. Я бы назвал `QueueTask` и передавал бы в аргумент непосредственно переменную типа `Task`

2022-05-01 21:38 UTC, Barugoo commented on internal/app/service/workers/accrual.go
> +		for {
А зачем нам здесь еще один цикл? Мы все равно не выйдем из `for range r.Tasks` пока не закроется канал `r.Tasks`

2022-05-01 21:39 UTC, Barugoo commented on internal/app/storage/postgres/auth.go
> +	}
Мб попробовать в обратном порядке - сначала мы делаем `INSERT`, если возвращается ошибка `ErrConflict`, то тогда уже возвращаем `ErrLoginRegistered`

2022-05-01 21:41 UTC, Barugoo commented on internal/app/storage/postgres/balances.go
> +		order.Sum = -order.Sum
В постгре кстати есть функция для получения модуля числа:
https://www.postgresqltutorial.com/postgresql-math-functions/postgresql-abs/

2022-05-01 21:42 UTC, Barugoo commented on internal/app/storage/postgres/balances.go
> +		order := &models.OrderBalance{}
Здесь необязательно объявлять указатель на `OrderBalance` и не придется разыменовывать его при аппенде ниже

2022-05-01 21:43 UTC, Barugoo commented on internal/app/storage/postgres/postgres.go
> +	if err := m.Up(); err != nil && err.Error() != "no change" {
Давай сравнивать возвращаемую ошибку с ошибкой из пакета, а не ее текст со строкой

2022-05-01 21:43 UTC, Barugoo requested changes
Хорошо, но есть замечания

2022-05-08 03:26 UTC, Barugoo commented on internal/app/api/orders.go
> +	if err := a.Services.AuthService.ValidUserID(userID); err != nil {
Под валидацией я имел в виду, скорее, просто проверить что у нас там чиселка пришла и что она положительная)

2022-05-08 03:27 UTC, Barugoo commented on internal/app/api/orders.go
> +	}
Давай уменьшать вложенность:
```go
if err != nil && !errors.Is(err, app.ErrOrderUploaded) {
    // я бы здесь еще логгирование впилил
    c.AbortWithStatus(app.ErrStatusCode(err))
    return
}
if errors.Is(err, app.ErrOrderUploaded) {
    c.Status(http.StatusOK)
    return c.Status(http.StatusOK)
}

2022-05-08 03:29 UTC, Barugoo commented on internal/app/service/jwtauth.go
> +			IssuedAt:  time.Now().Unix(),
Здесь не так важно, но вообще может выстрелить в каком-нибудь другом кейсе, где нам нужен одинаковый `time.Now`
На этих двух строчках эта функция вернет немножко разные значения, поэтому я бы сделал вот так:
```go
now := time.Now()
token := jwt.NewWithClaims(jwt.SigningMethodHS256, &tokenClaims{
		jwt.StandardClaims{
			ExpiresAt: now.Add(24 * time.Hour).Unix(),
			IssuedAt:  now.Unix(),

2022-05-08 03:30 UTC, Barugoo approved these changes
Отлично!

2022-05-12 06:11 UTC, merged